[project]
name = "egisso-forms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "costmaster1", email = "osoben1@yandex.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "flask-wtf>=1.3.0",
    "streamlit>=1.62.0",
]

[project.scripts]
egisso-forms = "egisso_forms:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
